### ISSUE TITLE
VpcId Parameter is a list instead of string

### ISSUE THREAD

**Issue by ortz** [thefactory/cloudformation-jenkins#4]
VpcId Parameter is configured as list instead of string that it should be
Replace
    "VpcId" : {
      "Description" : "VPC associated with the provided subnets",
      "Type" : "ListAWS::EC2::VPC::Id"
    },
With
    "VpcId" : {
      "Description" : "VPC associated with the provided subnets",
      "Type" : "AWS::EC2::VPC::Id"
    },

**Comment by mbabineau** [comment]
Good catch, thanks!
