### ISSUE TITLE
Issue with cron line

### ISSUE THREAD

**Issue by ghost** [thefactory/cloudformation-jenkins#5]
Should be 
"59 0 \* \* \* root jenkins-backup /var/lib/jenkins s3://{{s3_bucket}}/{{s3_prefix}}jenkins-`date +\\%Y\\%m\\%d\\%H\\%M.tar.gz` >> /var/log/jenkins-backup.log 2>&1\n"
Instead of
"59 0 \* \* root jenkins-backup /var/lib/jenkins s3://{{s3_bucket}}/{{s3_prefix}}jenkins-`date +\\%Y\\%m\\%d\\%H\\%M.tar.gz` >> /var/log/jenkins-backup.log 2>&1\n"
(Missing asterisk)

**Comment by mbabineau** [comment]
Doh, thanks for catching this
